name: Update the Keywords

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  push:
    branches:
      - master

jobs:
  my-job:
    if: (github.event_name == 'pull_request' &&
            github.event.pull_request.merged == true && 
            startsWith(github.event.pull_request.head.ref, 'post/')) ||
        (github.event_name == 'push' &&
            contains(github.event.head_commit.message, 'post'))
    runs-on: ubuntu-latest
    steps:
    - name: install-dependencies
      run: echo I will install all of them!